Repository client69/Hacktober-Open, pull requests merged in 2020-10, with the labels that each got.

#2 Update README.md
  README.md
Labels: hacktober-accepted, hacktoberfest-accepted

#3 Update README.md 2
  README.md
Labels: hacktoberfest-accepted

#4 Update README.md
  README.md
Labels: hacktoberfest-accepted

#5 Update README.md
  README.md
Labels: hacktoberfest-accepted

#6 Create mergesort-algo.cpp
  mergesort-algo.cpp
Labels: hacktoberfest-accepted

#7 Create quicksort-algo.cpp
  quicksort-algo.cpp
Labels: hacktoberfest-accepted

#8 Create radixsort-algo.cpp
  radixsort-algo.cpp
Labels: hacktoberfest-accepted

#9 Create externalsort-algo.cpp
  externalsort-algo.cpp
Labels: hacktoberfest-accepted

#11 add left rotate array js
  rotate-array-from-left.js
Labels: hacktoberfest-accepted

#10 Create Bubble_sort.c
  Bubble_sort.c
Labels: hacktoberfest-accepted

#13 countSort algorithm
  countSort.cpp
Labels: hacktoberfest-accepted

#12 create an array dimension value swapper in JS
  minimum-swapper-2.js
Labels: hacktoberfest-accepted

#16 Insertion Sort
  insertionSort.cpp
Labels: hacktoberfest-accepted

#15 Update README.md
  README.md
Labels: hacktoberfest-accepted

#14 Added Some number theory ques in cpp
  binary exponent loop.cpp
  binary exponent recursive.cpp
  et or pfi using seive way.cpp
  etf or phi in sqrt(n).cpp
  euclid extended.cpp
  euclidproblem.cpp
  gcd.cpp
  modular exponent loop.cpp
  modular exponent recursion.cpp
  no of div with seive.cpp
  no of div without seive.cpp
  sum of all div using seive.cpp
  sum of all prime using seive.cpp
Labels: hacktoberfest-accepted

#17 added KMP algo
  kmp_algo.cpp
Labels: hacktoberfest-accepted

#18 added djkstra algo
  djkshtra_algo.cpp
Labels: hacktoberfest-accepted

#19 added prims algo
  prims_algo.cpp
Labels: hacktoberfest-accepted

#20 added krusgal algo
  krusgal.cpp
Labels: hacktoberfest-accepted

#21 ll
  ll.cpp
Labels: hacktoberfest-accepted

#22 ll
  questions.cpp
Labels: good first issue, hacktoberfest-accepted

#23 ll
  AVL.cpp
  Gt$Node.class
  Gt.class
  Gt.java
  bit.cpp
Labels: hacktoberfest-accepted

#24 Create bankers_algorithm_safe_state.cpp
  bankers_algorithm_safe_state.cpp
Labels: hacktoberfest-accepted

#25 last
  New Text Document.txt
Labels: hacktoberfest-accepted

#26 Create TimSort.cpp
  TimSort.cpp
Labels: hacktoberfest-accepted

#31 Create AppWindow.java
  AppWindow.java
Labels: hacktoberfest-accepted

#30 Create kruskal.py
  kruskal.py
Labels: hacktoberfest-accepted

#29 Create dijkstra.py
  dijkstra.py
Labels: hacktoberfest-accepted

#27 Added cycle detection algorithm using cpp.
  cycle_detect.cpp
Labels: hacktoberfest-accepted

#32 Added two generic recursive functions with efficient solution
  combinationFormula.c
  efficientExponent.c
Labels: hacktoberfest-accepted

#28 Create prim.py
  prim.py
Labels: hacktoberfest-accepted

#33 adds function to identifying prime numbers in javascript
  prime_number.js
Labels: hacktoberfest-accepted

#34 insertion sort and stack operation
  insertionsort.c
  recordofdtuusingfile.c
  stackoperationusingarray.c
Labels: hacktoberfest-accepted

#35 Added a cp problem
  agressiveCows.cpp
Labels: hacktoberfest-accepted

#36 Added a cp problem
  inversionCount.cpp
Labels: hacktoberfest-accepted

#37 Add files via upload
  sudokuSolver.cpp
Labels: hacktoberfest-accepted

#38 Added bellmanFord
  bellmanFord.cpp
Labels: hacktoberfest-accepted

#39 Create clone-graph
  clone-graph
Labels: hacktoberfest-accepted

#40 Create clone
  clone
Labels: hacktoberfest-accepted

#41 Create cloning
  cloning
Labels: hacktoberfest-accepted

#42 Create graph_ques
  graph_ques
Labels: hacktoberfest-accepted

#43 Create Combination-Sum
  Combination-Sum
Labels: hacktoberfest-accepted

#44 my frist code of python
  variableprogram.py
Labels: hacktoberfest-accepted

#47 Create texttt.txt
  texttt.txt
Labels: hacktoberfest-accepted

#46 Create KadaneAlgorithm.py
  KadaneAlgorithm.py
Labels: hacktoberfest-accepted

#45 Create fibonacci_series.cpp
  fibonacci_series.cpp
Labels: hacktoberfest-accepted

#48 Update texttt.txt
  texttt.txt
Labels: hacktoberfest-accepted

#49 Update texttt.txt
  texttt.txt
Labels: hacktoberfest-accepted

#50 Update texttt.txt
  texttt.txt
Labels: hacktoberfest-accepted

#55 add converter to roman numerals
  to_roman_numerals.py
Labels: hacktoberfest-accepted

#54 Create LinkedListPalindrome.java
  LinkedListPalindrome.java
Labels: hacktoberfest-accepted

#53 Algorithm
  SelectionSort.cpp
Labels: hacktoberfest-accepted

#52 added bubble sort algorithm in Rust. Sotrs ints and strings.
  bubble.rs
Labels: hacktoberfest-accepted

#51 Binarytree program
  JPGtoPNG_Converter.py
  binarytree.c
Labels: hacktoberfest-accepted

#100 Create Helloworld.php
  Helloworld.php
Labels: hacktoberfest-accepted

#99 Create Linear_search.py
  Linear_search.py
Labels: hacktoberfest-accepted

#97 Tri-Digonal Matrix Algorithm for solving linear equations like Ax=b in matlab
  TDMA.m
Labels: hacktoberfest-accepted

#96 Create terraform-create-ec2.tf
  terraform-create-ec2.tf
Labels: hacktoberfest-accepted

#95 A simple number guesser game made using python :)
  numberguesser.py
Labels: hacktoberfest-accepted

#93 create linkedlist.cpp
  createaalinkedlist.cpp
  createalinkedlist.cpp
Labels: hacktoberfest-accepted

#92 Added Knapsack and Longest Increasing Subsequence Program
  Knapsack.cpp
  Longest_increaing_subseqeunce.cpp
Labels: hacktoberfest-accepted

#91 Infix to Postfix converter
  one.java
Labels: hacktoberfest-accepted

#90 Linear Search
  linearsearch.java
Labels: hacktoberfest-accepted

#89 R code
  linear-regression(grade prediction).R
Labels: hacktoberfest-accepted

#88 Rotating an Array
  RotateArray.java
Labels: hacktoberfest-accepted

#87 Maximum sum from sub-array and Expression Evaluation
  Expression_Evaluation.cpp
  Max_Subarray.py
Labels: hacktoberfest-accepted

#86 Tower Of Hanoi
  TOH.java
Labels: hacktoberfest-accepted

#85 Maximum in a Sliding Window
  sliding.java
Labels: hacktoberfest-accepted

#84 Added Heap Sort
  Heap Sort.cpp
Labels: hacktoberfest-accepted

#83 From this code we can implement the cli on our mobile app
  livecliterminal.py
Labels: hacktoberfest-accepted

#82 Rotate a singly linked list
  RotateList.cpp
Labels: hacktoberfest-accepted

#81 Create Automorphic Number
  Automorphic Number
Labels: hacktoberfest-accepted

#80 Create Binarysearch.py
  Binarysearch.py
Labels: hacktoberfest-accepted

#79 Added selection sort in java
  SelectionSort.java
Labels: hacktoberfest-accepted

#76 merge sort in python
  merge_sort.py
  random_num_generator.py
Labels: hacktoberfest-accepted

#77 Update SelectionSort.cpp
  SelectionSort.cpp
Labels: hacktoberfest-accepted

#78 Create insertion-sort.py
  insertion-sort.py
Labels: hacktoberfest-accepted

#75 Update cycle_detect.cpp
  cycle_detect.cpp
Labels: hacktoberfest-accepted

#74 TowerOfHanoi-Java
  TowerOfHanoi.java
Labels: hacktoberfest-accepted

#72 Create CountPrimesUsingSieve.py
  CountPrimesUsingSieve.py
Labels: hacktoberfest-accepted

#71 Added Heapsort and Hashjoin in Go
  HashJoin.go
  HeapSort.go
Labels: hacktoberfest-accepted

#70 Insertion Sort Added
  insertion_sort.cpp
Labels: hacktoberfest-accepted

#69 Add stack with linked list
  Stack_LinkedList.cpp
Labels: hacktoberfest-accepted

#68 Added Topological Sort algorithm
  topologicalSort.cpp
Labels: hacktoberfest-accepted

#67 Added code for the algorithm - Binary Search
  SchedulingAlgo.cpp
  binarySearch.cpp
Labels: hacktoberfest-accepted

#66 JS Quick Sort algo added
  quick_sort.js
Labels: hacktoberfest-accepted

#65 Added bubble_sort
  bubble_sort.py
Labels: hacktoberfest-accepted

#64 A queue script in java
  myqueue.java
Labels: hacktoberfest-accepted

#63 Create permutermIndex.py
  permutermIndex.py
Labels: hacktoberfest-accepted

#62 Created prime checker program
  prime_checker.java
Labels: hacktoberfest-accepted

#61 added romanize.js
  romanize.js
Labels: hacktoberfest-accepted

#60 Create binary_search.c
  binary_search.c
Labels: hacktoberfest-accepted

#59 Add a binary search code in Python
  binary_search.py
Labels: hacktoberfest-accepted

#57 Dutch-flag Algorithm
  dutchflag.cpp
Labels: hacktoberfest-accepted

#115 Popular CP problem
  coinTower.cpp
Labels: hacktoberfest-accepted

#116 Strictly Connected Components
  SCC.cpp
Labels: hacktoberfest-accepted

#117 CodeChef Problem
  Covid.cpp
Labels: hacktoberfest-accepted

#118 IB problem
  version.cpp
Labels: hacktoberfest-accepted

#134 Create fibonacci.js
  fibonacci.js
Labels: hacktoberfest-accepted

#135 Create order_by_index.js
  order_by_index.js
Labels: hacktoberfest-accepted

#136 Create reverse_str.js
  reverse_str.js
Labels: hacktoberfest-accepted

#137 Create given_sum.js
  given_sum.js
Labels: enhancement, good first issue, hacktober, hacktoberfest-accepted

#138 Update AVL.cpp
  AVL.cpp
Labels: good first issue, hacktober, hacktober-accepted, hacktoberfest-accepted

#139 Update AppWindow.java
  AppWindow.java
Labels: hacktoberfest-accepted

#140 Update Covid.cpp
  Covid.cpp
Labels: hacktober, hacktober-accepted, hacktoberfest-accepted

#141 Update Helloworld.php
  Helloworld.php
Labels: good first issue, hacktober, hacktober-accepted, hacktoberfest-accepted

#143 using Prim's Minimum Spanning Tree (MST) algorithm for graph representation
  MSP.py
Labels: hacktoberfest-accepted

#142 longest palindrome string added
  longestPalindrome.cpp
Labels: hacktoberfest-accepted

#133 Defish Image Code in CPP
  defish_images.cpp
Labels: hacktoberfest-accepted

#132 Adding Clock.java to Hacktober-Open
  Clock.java
Labels: hacktoberfest-accepted

#131 Create node-rectangle.js
  node-rectangle.js
Labels: hacktoberfest-accepted

#130 create balanced_paranthesis.py
  balanced_paranthesis.py
Labels: hacktoberfest-accepted

#129 Create calculator.py
  calculator.py
Labels: hacktoberfest-accepted

#128 GuessTheNumber
  guessTheNumber.c
Labels: hacktoberfest-accepted

#127 Add: Sort using rotation( Larry's Array)
  Larry's-Array.py
Labels: hacktoberfest-accepted

#126 Add files via upload
  BST.py
Labels: hacktoberfest-accepted

#125 Create ternarySearch.cpp
  ternarySearch.cpp
Labels: hacktoberfest-accepted

#124 Create Siteblocker.py
  Siteblocker.py
Labels: hacktoberfest-accepted

#123 Add the file to the main branch
  Inorder_Successor_BinaryTree.py
Labels: hacktoberfest-accepted

#122 Added a folder for LeetCode Solutions in Python
  LeetCode  Solutions/1029. Two City Scheduling/TwoCityScheduling.py
  LeetCode  Solutions/1029. Two City Scheduling/readme.md
  LeetCode  Solutions/1089. Duplicate Zeros/DuplicateZeros.py
  LeetCode  Solutions/1089. Duplicate Zeros/readme.md
  LeetCode  Solutions/1108. Defanging an IP Address/DefanginIP.py
  LeetCode  Solutions/1108. Defanging an IP Address/readme.md
  LeetCode  Solutions/1295. Find Numbers with Even Number of Digits/EvenNoOfDigits.py
  LeetCode  Solutions/1295. Find Numbers with Even Number of Digits/readme.md
  LeetCode  Solutions/226. Invert Binary Tree/InvertBinaryTree.py
  LeetCode  Solutions/226. Invert Binary Tree/readme.md
  LeetCode  Solutions/231. Power of Two/PowerOfTwo.py
  LeetCode  Solutions/231. Power of Two/readme.md
  LeetCode  Solutions/237. Delete Node in a Linked List/DeleteNodeLinkedList.py
  LeetCode  Solutions/237. Delete Node in a Linked List/readme.md
  LeetCode  Solutions/27. Remove Element/RemoveElement.py
  LeetCode  Solutions/27. Remove Element/readme.md
  LeetCode  Solutions/344. Reverse String/ReverseString.py
  LeetCode  Solutions/344. Reverse String/readme.md
  LeetCode  Solutions/406. Queue Reconstruction by Height/QueueReconstructionHeight.py
  LeetCode  Solutions/406. Queue Reconstruction by Height/readme.md
  LeetCode  Solutions/485. Max Consecutive Ones/MaxConsecutiveOnes.py
  LeetCode  Solutions/485. Max Consecutive Ones/README.md
  LeetCode  Solutions/518. Coin Change 2/CoinChange2.py
  LeetCode  Solutions/518. Coin Change 2/readme.md
  LeetCode  Solutions/528. Random Pick with Weight/RandomPickWeight.py
  LeetCode  Solutions/528. Random Pick with Weight/readme.md
  LeetCode  Solutions/75. Sort Colors/SortColors.py
  LeetCode  Solutions/75. Sort Colors/readme.md
  LeetCode  Solutions/88. Merge Sorted Array/MergeSortedArray.py
  LeetCode  Solutions/88. Merge Sorted Array/readme.md
  LeetCode  Solutions/977. Squares of a Sorted Array/SquaresSorted.py
  LeetCode  Solutions/977. Squares of a Sorted Array/readme.md
Labels: hacktoberfest-accepted

#121 Core
  core.php
Labels: hacktoberfest-accepted

#120 created and merge stoogesort.cpp
  stoogesort.cpp
Labels: hacktoberfest-accepted

#119 Linked list implementation in C
  linked_list.c
Labels: hacktoberfest-accepted

#114 Create quick_sort.java
  quick_sort.java
Labels: hacktoberfest-accepted

#113 Update README.md
  README.md
Labels: hacktoberfest-accepted

#112 added stone paper scissor
  StonePaperScissors.py
Labels: hacktoberfest-accepted

#111 Searching-Java
  Searching.java
Labels: hacktoberfest-accepted

#110 added greedy algorithm in c++
  greedyalgorithum.c
Labels: hacktoberfest-accepted

#109 Added a p-time prime test and deleted empty text document
  New Text Document.txt
  aks prime test.py
Labels: hacktoberfest-accepted

#108 Create SimpleSnakeGame.cpp
  SimpleSnakeGame.cpp
Labels: hacktoberfest-accepted

#107 Add files via upload
  HouseRobber.java
  KnapSack/KnapSackZeroOneRecursive.java
Labels: hacktoberfest-accepted

#106 it calculates ur bmi for u :}}
  bmi.py
Labels: hacktoberfest-accepted

#104 SymmetricTree.java
  PathSum.py
  SymmetricTree.java
Labels: hacktoberfest-accepted

#103 Update prims_algo.cpp
  prims_algo.cpp
Labels: hacktoberfest-accepted

#102 quick sort algorithm c++
  quick_sort.cpp
Labels: hacktoberfest-accepted

#180 Hackfest Question hackerrank
  ArrayOfObject in Java
  Game Of Maximization(Hackerrank Hackfest 2020)/Question.pdf
  Game Of Maximization(Hackerrank Hackfest 2020)/Solution.java
  Java_Leap_year/demo_2.java
Labels: hacktoberfest-accepted

#178 Create Studentform.html
  Studentform.html
Labels: hacktoberfest-accepted

#177 Create form.html
  form.html
Labels: hacktoberfest-accepted

#176 Binary search java
  BinarySearchInJava.java
Labels: hacktoberfest-accepted

#175 Add files via upload
  QueenAttack.py
Labels: hacktoberfest-accepted

#174 Verify if a char is a valid number.
  is_real_number.c
Labels: hacktoberfest-accepted

#173 Add file cses missing number
  missing-number.py
Labels: hacktoberfest-accepted

#172 Create SelectionSort.py
  SelectionSort.py
Labels: hacktoberfest-accepted

#171 Factorial Of Large Number
  FactLargeNo.c
Labels: hacktoberfest-accepted

#170 arrayprogramAdded
  arrQ.cpp
Labels: hacktoberfest-accepted

#169 Rotate LinkedList
  RotateLinkedList.java
Labels: hacktoberfest-accepted

#168 Create reverseAString.js
  reverseAString.js
Labels: hacktoberfest-accepted

#167 Adds MinSwapsToSortArray.java
  MinSwapsToSortArray.java
Labels: hacktoberfest-accepted

#166 program to find duplicate word in a vector . please merge my program for hacktoberfest. THANKSTOBER.
  copyfile/copyfile.cpp
Labels: hacktoberfest-accepted

#165 Uptated to print correct hello world
  Helloworld.php
Labels: hacktoberfest-accepted
